### ISSUE TITLE
Runing on armhf gcmsiv overflows int

### ISSUE THREAD

**Issue by nanu-c** [agl/gcmsiv#4]
```
# github.com/agl/gcmsiv
/gopath/path0/pkg/mod/github.com/agl/gcmsiv@v0.0.0-20190418185415-e8dcd2f151dc/gcmsiv.go:455:20: constant 68719476736 overflows int
/gopath/path0/pkg/mod/github.com/agl/gcmsiv@v0.0.0-20190418185415-e8dcd2f151dc/gcmsiv.go:459:25: constant 2305843009213693951 overflows int
/gopath/path0/pkg/mod/github.com/agl/gcmsiv@v0.0.0-20190418185415-e8dcd2f151dc/gcmsiv.go:475:25: constant 2305843009213693951 overflows int
/gopath/path0/pkg/mod/github.com/agl/gcmsiv@v0.0.0-20190418185415-e8dcd2f151dc/gcmsiv.go:479:45: constant 68719476752 overflows int
```

**Comment by Blackoverflow** [comment]
The type int is int32 on armhf, instead of int64.
[This commit](https://github.com/Blackoverflow/gcmsiv/commit/20af2af977ff5ea86822779c61227b2810248e3d) is able to prevent the overflow, but there has to be a better way.

I think those constants need to have other values on armhf, but which values?

**Comment by agl** [comment]
This is the repository for the AES-GCM-SIV spec. The reference code is not intended for anything other than generating test vectors for inclusion in the RFC.
